# SPDX-License-Identifier: Apache-2.0
"""Universal provider skill contract — discover through rollback."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ProviderSkill(Protocol):
    provider: str
    supported_operations: list[str]

    def discover(self, *, force: bool = False) -> dict[str, Any]: ...
    def resolve_target(self, *, user_request: str, target_hints: list[str] | None = None) -> dict[str, Any]: ...
    def plan(self, *, operation: str, target: Any, context: dict[str, Any] | None = None) -> Any: ...
    def dry_run(self, plan: Any) -> Any: ...
    def execute(self, plan: Any, *, approved: bool, before_snapshot: dict[str, Any] | None = None, approved_at: str | None = None, request_id: str = "provider-skill") -> Any: ...
    def collect_evidence(self, result: Any, *, approved_at: str | None = None) -> Any: ...
    def verify(self, *, operation: str, before: dict[str, Any], after: dict[str, Any], evidence_bundle: Any, approved_at: str | None = None, readonly_artifact: dict[str, Any] | None = None) -> Any: ...
    def diagnose_failure(self, evidence: Any) -> Any: ...
    def propose_fix(self, diagnosis: Any, *, target_name: str) -> Any: ...


def skill_supports(skill: Any, method: str) -> bool:
    return callable(getattr(skill, method, None))
