/** Generates MC_PANEL_AUDIT.md — run: npx tsx web/lib/missionControl/generatePanelAudit.ts */

import * as fs from "node:fs";
import * as path from "node:path";

import {
  ADVANCED_SETTINGS_VIEW_IDS,
  MAIN_NAV_VIEW_IDS,
  MERGED_INTO_PRIMARY,
} from "./flatNavigation";
import { MISSION_CONTROL_VIEWS, VIEW_LABELS } from "./views";

const REPO_ROOT = path.resolve(import.meta.dirname, "../../..");
const OUT = path.join(REPO_ROOT, "MC_PANEL_AUDIT.md");

function classify(view: string): string {
  if (MAIN_NAV_VIEW_IDS.has(view as never)) return "keep_surface";
  if (ADVANCED_SETTINGS_VIEW_IDS.has(view as never)) return "settings";
  if (MERGED_INTO_PRIMARY[view]) return "merge";
  return "search_only";
}

const lines: string[] = [
  "# Mission Control panel audit",
  "",
  "_Generated by `npx tsx web/lib/missionControl/generatePanelAudit.ts`. Do not hand-edit classifications — regenerate after nav changes._",
  "",
  "## Summary",
  "",
  `| Metric | Count |`,
  `|--------|-------|`,
  `| Total registered views | ${MISSION_CONTROL_VIEWS.length} |`,
  `| Main navigation (everyday) | ${MAIN_NAV_VIEW_IDS.size} |`,
  `| Advanced settings (diagnostics) | ${ADVANCED_SETTINGS_VIEW_IDS.size} |`,
  `| Merged into primary nav | ${Object.keys(MERGED_INTO_PRIMARY).length} |`,
  `| Search-only (power panels) | ${MISSION_CONTROL_VIEWS.filter((v) => classify(v) === "search_only").length} |`,
  "",
  "## Classifications",
  "",
  "| View | Label | Class | Notes |",
  "|------|-------|-------|-------|",
];

for (const view of MISSION_CONTROL_VIEWS) {
  const cls = classify(view);
  const label = String(VIEW_LABELS[view as keyof typeof VIEW_LABELS] ?? view);
  let notes = "";
  if (cls === "merge") notes = `→ ${MERGED_INTO_PRIMARY[view]}`;
  if (cls === "search_only") notes = "HumanCentered / certification panel; jump via search";
  lines.push(`| ${view} | ${label.replace(/\|/g, "\\|")} | ${cls} | ${notes} |`);
}

lines.push("");
lines.push("## Navigation model");
lines.push("");
lines.push("- **Main nav**: flat sidebar groups (Work, Build, Connect, System) — no simple/advanced toggle.");
lines.push("- **Advanced settings**: configuration and diagnostics only; collapsible at sidebar bottom.");
lines.push("- **Search**: all registered views reachable via sidebar search.");
lines.push("- **Merged**: duplicate agent/approval surfaces fold into Agents and Approvals.");
lines.push("");

fs.writeFileSync(OUT, lines.join("\n"), "utf8");
console.log(`Wrote ${OUT}`);
