# SPDX-License-Identifier: Apache-2.0
"""PR generation runtime — governed PR drafts."""

from __future__ import annotations

from typing import Any


def generate_pr_draft(
    *,
    preflight: dict[str, Any],
    execution: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Generate PR draft metadata — creation requires separate approval."""
    task = preflight.get("task") or {}
    patch = preflight.get("patch_proposal") or {}
    validation = (execution or {}).get("validation") or {}
    files = patch.get("files_affected") or task.get("affected_files") or []
    title = task.get("title") or "Governed engineering fix"
    return {
        "ok": True,
        "status": "pr_draft",
        "title": title,
        "summary": _build_summary(task, patch),
        "linked_issue": task.get("issue_number"),
        "rollout_notes": "Deploy after CI validation and human merge approval.",
        "risk_notes": f"Risk tier: {preflight.get('risk_tier')} — {', '.join(patch.get('risk_areas') or [])[:200]}",
        "rollback_instructions": patch.get("rollback_strategy") or "Revert branch and restore rollback snapshot.",
        "evidence_references": [
            preflight.get("preflight_id"),
            (execution or {}).get("execution_id"),
        ],
        "validation_evidence": {
            "status": validation.get("validation_status"),
            "pass_count": validation.get("pass_count"),
            "fail_count": validation.get("fail_count"),
        },
        "files": files,
        "body": format_pr_body(title=title, task=task, patch=patch, validation=validation, files=files),
        "merge_enabled": False,
        "auto_merge": False,
    }


def _build_summary(task: dict[str, Any], patch: dict[str, Any]) -> str:
    return patch.get("patch_summary") or task.get("proposed_fix") or task.get("problem_summary") or "Governed engineering change."


def format_pr_body(
    *,
    title: str,
    task: dict[str, Any],
    patch: dict[str, Any],
    validation: dict[str, Any],
    files: list[str],
) -> str:
    lines = [
        f"## {title}",
        "",
        task.get("problem_summary") or "",
        "",
        "### Summary",
        patch.get("patch_summary") or task.get("proposed_fix") or "",
        "",
        "### Files",
        *[f"- `{f}`" for f in files[:12]],
        "",
        "### Validation",
        f"- Status: {validation.get('validation_status', 'pending')}",
        f"- Pass/fail: {validation.get('pass_count', 0)}/{validation.get('fail_count', 0)}",
        "",
        "### Risk",
        patch.get("risk_areas", ["LOW — scoped engineering change"])[0] if patch.get("risk_areas") else "LOW",
        "",
        "### Rollback",
        patch.get("rollback_strategy") or "Revert branch.",
        "",
        "*Generated by AethOS governed engineering execution — no auto-merge.*",
    ]
    return "\n".join(lines)
