# SPDX-License-Identifier: Apache-2.0
"""Capability registry — canonical operational capability inventory."""

from __future__ import annotations

from typing import Any

# Platform capabilities beyond provider registry
PLATFORM_CAPABILITIES: list[dict[str, Any]] = [
    {
        "id": "browser_evidence",
        "name": "Browser evidence capture",
        "category": "observation",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "telegram_research",
        "name": "Telegram research runtime",
        "category": "channels",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "sandbox_execution",
        "name": "Sandbox execution",
        "category": "engineering",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "replay_reconstruction",
        "name": "Replay reconstruction",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "engineering_execution",
        "name": "Engineering readonly execution",
        "category": "engineering",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "mutation_reconciliation",
        "name": "Mutation reconciliation",
        "category": "reconciliation",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "rollback_verification",
        "name": "Rollback verification",
        "category": "reconciliation",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "docker_container_intelligence",
        "name": "Docker container intelligence",
        "category": "infrastructure",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "kubernetes_runtime_intelligence",
        "name": "Kubernetes runtime intelligence",
        "category": "infrastructure",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "topology_intelligence",
        "name": "Runtime topology intelligence",
        "category": "infrastructure",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "infrastructure_reconciliation",
        "name": "Infrastructure reconciliation",
        "category": "infrastructure",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "runtime_supervision",
        "name": "Runtime supervision",
        "category": "infrastructure",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "infrastructure_confidence",
        "name": "Infrastructure confidence integrity",
        "category": "infrastructure",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "continuous_verification",
        "name": "Continuous verification runtime",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "recovery_orchestration",
        "name": "Recovery orchestration",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "drift_intelligence",
        "name": "Runtime drift intelligence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "predictive_operations",
        "name": "Predictive operational intelligence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "production_confidence",
        "name": "Production confidence runtime",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "reliability_memory",
        "name": "Operational reliability memory",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "conversational_synthesis",
        "name": "Conversational synthesis runtime",
        "category": "human",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "human_trust_presentation",
        "name": "Human trust & confidence restraint",
        "category": "human",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "presentation_safety",
        "name": "Presentation safety",
        "category": "human",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "recommendation_intelligence",
        "name": "Recommendation intelligence",
        "category": "human",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "conversational_elegance",
        "name": "Conversational elegance",
        "category": "human",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "conversational_reliability",
        "name": "Conversational reliability runtime",
        "category": "human",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "intent_reliability",
        "name": "Intent contract reliability",
        "category": "human",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "presentation_integrity",
        "name": "Presentation integrity",
        "category": "human",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "recommendation_refinement",
        "name": "Recommendation refinement",
        "category": "human",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "human_trust_language",
        "name": "Human trust language",
        "category": "human",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "conversational_convergence",
        "name": "Conversational convergence runtime",
        "category": "human",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "interaction_layers",
        "name": "Interaction layer surface matrix",
        "category": "human",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "conversational_qualification",
        "name": "Production conversational qualification",
        "category": "human",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "production_execution_truth",
        "name": "Production execution truth runtime",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "provider_truth_convergence",
        "name": "Tier 1 provider truth convergence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "rollback_integrity",
        "name": "Rollback integrity runtime",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "runtime_stabilization_intelligence",
        "name": "Runtime stabilization intelligence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "infrastructure_truth",
        "name": "Infrastructure truth convergence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "reality_harness_v4",
        "name": "Reality harness 4.0",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "sustained_verification",
        "name": "Sustained operational verification",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "production_execution_realism",
        "name": "Production execution realism runtime",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "runtime_reconciliation",
        "name": "Runtime reconciliation runtime",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "operational_patience_intelligence",
        "name": "Operational patience intelligence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "runtime_decay_intelligence",
        "name": "Runtime decay intelligence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "provider_runtime_truth",
        "name": "Provider runtime truth",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "sustained_verification_windows",
        "name": "Sustained verification windows",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "recovery_truth_convergence",
        "name": "Recovery truth convergence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "reality_harness_v41",
        "name": "Reality harness 4.1",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "runtime_truth_convergence",
        "name": "Runtime truth convergence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "operational_stability_windows",
        "name": "Operational stability windows",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "recovery_convergence",
        "name": "Recovery convergence intelligence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "long_tail_operational_decay",
        "name": "Long-tail operational decay",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "adaptive_sustained_verification",
        "name": "Adaptive sustained verification",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "runtime_convergence_cognition",
        "name": "Runtime convergence cognition",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "infrastructure_intuition",
        "name": "Infrastructure intuition",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "temporal_confidence",
        "name": "Temporal confidence evolution",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "kubernetes_convergence",
        "name": "Kubernetes convergence cognition",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "replay_continuity_intelligence",
        "name": "Replay continuity intelligence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "long_tail_operational_memory",
        "name": "Long-tail operational memory",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "reality_harness_v42",
        "name": "Reality harness 4.2",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "recovery_continuity_intelligence",
        "name": "Recovery continuity intelligence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "temporal_operational_trust",
        "name": "Temporal operational trust",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "infrastructure_convergence",
        "name": "Infrastructure convergence cognition",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "replay_persistence",
        "name": "Replay persistence intelligence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "adaptive_runtime_verification",
        "name": "Adaptive runtime verification",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "long_tail_stability",
        "name": "Long-tail stability intelligence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "operational_resilience_cognition",
        "name": "Operational resilience cognition",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "infrastructure_fragility",
        "name": "Infrastructure fragility intelligence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "temporal_trust_evolution",
        "name": "Temporal trust evolution 2.0",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "kubernetes_resilience",
        "name": "Kubernetes resilience cognition",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "replay_resilience_intelligence",
        "name": "Replay resilience intelligence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "long_tail_resilience_memory",
        "name": "Long-tail resilience memory",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "reality_harness_v43",
        "name": "Reality harness 4.3",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "operational_resilience",
        "name": "Operational resilience (11.6.3)",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "runtime_fragility",
        "name": "Runtime fragility intelligence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "sustained_trust_evolution",
        "name": "Sustained trust evolution",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "kubernetes_runtime_durability",
        "name": "Kubernetes runtime durability",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "replay_resilience",
        "name": "Replay resilience cognition",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "long_tail_resilience",
        "name": "Long-tail resilience memory",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "predictive_operational_cognition",
        "name": "Predictive operational cognition",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "fragility_acceleration",
        "name": "Fragility acceleration intelligence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "replay_erosion_forecasting",
        "name": "Replay erosion forecasting",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "topology_stability_forecasting",
        "name": "Topology stability forecasting",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "operational_fatigue_intelligence",
        "name": "Operational fatigue intelligence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "sustained_stability_forecasting",
        "name": "Sustained stability forecasting",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "reality_harness_v44",
        "name": "Reality harness 4.4",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "runtime_fragility_intelligence",
        "name": "Runtime fragility intelligence (11.6.4)",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "degradation_acceleration",
        "name": "Degradation acceleration",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "replay_erosion_intelligence",
        "name": "Replay erosion intelligence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "topology_fragility_forecasting",
        "name": "Topology fragility forecasting",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "operational_fatigue_cognition",
        "name": "Operational fatigue cognition",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "predictive_runtime_stability",
        "name": "Predictive runtime stability",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "long_tail_operational_forecasting",
        "name": "Long-tail operational forecasting (11.4.7)",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "operational_survivability",
        "name": "Operational survivability",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "replay_longevity_forecasting",
        "name": "Replay longevity forecasting",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "topology_sustainability",
        "name": "Topology sustainability",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "resilience_exhaustion",
        "name": "Resilience exhaustion cognition",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "autonomous_stability_cognition",
        "name": "Autonomous stability cognition",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "reality_harness_v45",
        "name": "Reality harness 4.5",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "long_tail_runtime_cognition",
        "name": "Long-tail runtime cognition (11.6.5)",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "runtime_survivability_intelligence",
        "name": "Runtime survivability intelligence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "operational_endurance",
        "name": "Operational endurance cognition",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "replay_continuity_survivability",
        "name": "Replay continuity survivability",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "topology_endurance_forecasting",
        "name": "Topology endurance forecasting",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "resilience_exhaustion_intelligence",
        "name": "Resilience exhaustion intelligence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "conversational_operational_grounding",
        "name": "Conversational operational grounding (11.7)",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "continuity_reconstruction",
        "name": "Continuity reconstruction",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "operational_context_memory",
        "name": "Operational context memory",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "governance_restraint_runtime",
        "name": "Governance restraint runtime",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "conversational_realism",
        "name": "Conversational realism",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "telegram_session_persistence",
        "name": "Telegram session persistence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "operational_partner_presence",
        "name": "Operational partner presence",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "operational_thread_integrity",
        "name": "Operational thread integrity (11.7.2)",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "conversational_realism_polish",
        "name": "Conversational realism polish (11.7.3)",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "cross_surface_reality_convergence",
        "name": "Cross-surface reality convergence (11.7.4)",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "live_operational_grounding",
        "name": "Live operational grounding (11.7.5)",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "operational_entity_runtime",
        "name": "Operational entity realism (11.7.6)",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "operational_progression_runtime",
        "name": "Operational progression realism (11.7.7)",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "investigative_continuity_runtime",
        "name": "Investigative continuity realism (11.7.8)",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "durable_agent_jobs_runtime",
        "name": "Durable agent jobs (11.7.9)",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "job_truth_runtime",
        "name": "Job status honesty (11.8.0)",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "telegram_validation_harness",
        "name": "Telegram long-session validation (11.8.0)",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "external_execution_truth_runtime",
        "name": "External execution truth (11.8.1)",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
    {
        "id": "telegram_soak_runtime",
        "name": "Telegram soak validation (11.8.2)",
        "category": "reliability",
        "claimed": True,
        "provider": None,
    },
]

TIER1_PROVIDERS = frozenset({"railway", "github", "vercel"})
TIER2_PROVIDERS = frozenset({"docker", "kubernetes", "aws"})
TIER3_PROVIDERS = frozenset({
    "stripe", "slack", "discord", "datadog", "grafana", "sentry",
    "pagerduty", "supabase", "neon", "redis", "postgresql", "cloudflare", "jira", "linear",
})


def list_provider_capabilities() -> list[dict[str, Any]]:
    from aethos_core.providers.base.provider_registry import ProviderRegistry

    entries: list[dict[str, Any]] = []
    for spec in ProviderRegistry.list_specs():
        tier = "tier1" if spec.name in TIER1_PROVIDERS else "tier2" if spec.name in TIER2_PROVIDERS else "tier3"
        for op, cap in spec.capabilities.items():
            if not cap.mutation:
                continue
            entries.append({
                "id": f"{spec.name}:{op}",
                "name": f"{spec.label} — {op.replace('_', ' ')}",
                "category": "provider_mutation",
                "provider": spec.name,
                "operation": op,
                "claimed": cap.enabled,
                "requires_approval": cap.requires_approval,
                "hardening_tier": tier,
            })
    return entries


def list_all_capabilities() -> list[dict[str, Any]]:
    return list_provider_capabilities() + [dict(c) for c in PLATFORM_CAPABILITIES]


def provider_hardening_priority() -> list[dict[str, Any]]:
    from aethos_core.providers.base.provider_registry import ProviderRegistry

    registered = {s.name for s in ProviderRegistry.list_specs()}
    priorities: list[dict[str, Any]] = []
    for name in sorted(TIER1_PROVIDERS):
        priorities.append({
            "provider": name,
            "tier": "tier1",
            "priority": "critical",
            "registered": name in registered,
            "hardening_status": "in_progress" if name in registered else "not_registered",
        })
    for name in sorted(TIER2_PROVIDERS):
        priorities.append({
            "provider": name,
            "tier": "tier2",
            "priority": "next",
            "registered": name in registered,
            "hardening_status": "deferred" if name not in registered else "partial",
        })
    return priorities
