#!/usr/bin/env python3
"""
Merge `.env.bak` into `.env` without overwriting existing keys in `.env`.

Current `.env` values always win on conflict. Output is sorted by key (case-insensitive)
with a generated header. Comments from source files are not preserved.

Usage:
  python scripts/merge_aethos_env.py              # writes .env, backs up first
  python scripts/merge_aethos_env.py --dry-run    # print stats only
"""

from __future__ import annotations

import argparse
import shutil
from datetime import datetime, timezone
from pathlib import Path


def _strip_quotes(val: str) -> str:
    v = val.strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in ('"', "'"):
        return v[1:-1]
    return v


def parse_env_file(path: Path) -> dict[str, str]:
    """Parse KEY=value assignments; last occurrence per file wins; skip comments and blanks."""
    text = path.read_text(encoding="utf-8", errors="replace")
    out: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].strip()
        if "=" not in line:
            continue
        key, _, rest = line.partition("=")
        k = key.strip()
        if not k:
            continue
        out[k] = _strip_quotes(rest)
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description="Merge .env.bak into .env (current wins on overlap).")
    parser.add_argument("--dry-run", action="store_true", help="Do not write files; print summary.")
    parser.add_argument(
        "--bak",
        type=Path,
        default=Path(".env.bak"),
        help="Backup env file to merge from (default: .env.bak)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(".env"),
        help="Output env file (default: .env)",
    )
    args = parser.parse_args()

    repo = Path(__file__).resolve().parents[1]
    cur_path = repo / args.out
    bak_path = repo / args.bak

    if not cur_path.is_file():
        print(f"Missing {cur_path}")
        return 1
    if not bak_path.is_file():
        print(f"Missing {bak_path}")
        return 1

    current = parse_env_file(cur_path)
    backup = parse_env_file(bak_path)

    merged: dict[str, str] = dict(backup)
    merged.update(current)

    added_keys = sorted(set(merged) - set(current), key=str.lower)
    overlap = sorted(set(current) & set(backup), key=str.lower)

    print(f"Current keys: {len(current)}")
    print(f"Backup keys:  {len(backup)}")
    print(f"Merged keys:  {len(merged)}")
    print(f"New from backup (not in current): {len(added_keys)}")
    print(f"Overlapping keys (kept from current): {len(overlap)}")

    if added_keys and len(added_keys) <= 40:
        print("Added:", ", ".join(added_keys))
    elif added_keys:
        print("Added (first 40):", ", ".join(added_keys[:40]), "...")

    if args.dry_run:
        return 0

    backup_dest = repo / ".env.pre_full_backup"
    shutil.copy2(cur_path, backup_dest)
    print(f"Backed up current .env to {backup_dest.relative_to(repo)}")

    header = (
        f"# AethOS environment — merged {datetime.now(timezone.utc).isoformat()}Z\n"
        "# Generated by scripts/merge_aethos_env.py\n"
        "# Order: all keys from .env.bak plus .env (current wins duplicates); sorted by key.\n"
        "# Review secrets before committing anything; .env must stay gitignored.\n"
        "\n"
    )
    lines = [header]
    for k in sorted(merged.keys(), key=lambda x: (x.lower(), x)):
        v = merged[k]
        # Minimal escaping: if newline or quote, use double quotes
        if "\n" in v or '"' in v:
            escaped = v.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'{k}="{escaped}"\n')
        else:
            lines.append(f"{k}={v}\n")

    out_path = repo / args.out
    out_path.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {out_path.relative_to(repo)} ({len(merged)} variables)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
