# SPDX-License-Identifier: Apache-2.0
"""
FIX 135 — Frozen Mission Control operator console (machine-readable).

Scope: FIX 128–135 operator surfaces (cross-lane observability + approval inbox).
Legacy Mission Control panels (runtime-actions, Railway job controls) are out of freeze
scope until explicitly re-gated.
"""

from __future__ import annotations

import re
from typing import Final

from aethos_core.mission_control.approval_inbox.action_safety_contract import (
    FORBIDDEN_DIRECT_PROVIDER_CALLS,
    FORBIDDEN_MC_UI_CONTROLS_FIX_134,
    REQUIRED_UI_APPROVAL_ENTRYPOINT,
)

MISSION_CONTROL_UI_FREEZE_FIX: Final[str] = "FIX 135"
MISSION_CONTROL_UI_FROZEN: Final[bool] = True
MISSION_CONTROL_UI_SCHEMA_VERSION: Final[str] = "mission_control_operator_console_v1"

MISSION_CONTROL_SHIPPED_FIXES: Final[tuple[str, ...]] = (
    "FIX 128",
    "FIX 129",
    "FIX 130",
    "FIX 131",
    "FIX 132",
    "FIX 133",
    "FIX 134",
    "FIX 135",
    "FIX 136",
    "FIX 137",
    "FIX 137B",
    "FIX 138",
    "FIX 139",
    "FIX 140",
    "FIX 141",
    "FIX 142",
    "FIX 143",
    "FIX 144",
    "FIX 145",
    "FIX 146",
    "FIX 147",
    "FIX 148",
    "FIX 149",
    "FIX 150",
    "FIX 151",
    "FIX 152",
    "FIX 153",
    "FIX 154",
    "FIX 155",
    "FIX 156",
    "FIX 157",
    "FIX 158",
    "FIX 159",
    "FIX 160",
    "FIX 161",
    "FIX 162",
)

MISSION_CONTROL_UI_INVARIANT: Final[str] = (
    "mission_control_ui_approval → resolve_chat_turn → existing lane logic → audit receipt; "
    "never direct provider mutation APIs"
)

# Operator console views frozen at FIX 135 (read-only + governed approval only).
FROZEN_OPERATOR_CONSOLE_VIEWS: Final[tuple[str, ...]] = (
    "cross-lane-operations",
    "approval-inbox",
    "mission-job-replay",
)

FROZEN_UI_COMPONENT_PATHS: Final[tuple[str, ...]] = (
    "web/components/missionControl/CrossLaneOperationsPanel.tsx",
    "web/components/missionControl/CrossLaneLaneDrilldownPanel.tsx",
    "web/components/missionControl/ApprovalInboxPanel.tsx",
    "web/components/missionControl/JobReplayPanel.tsx",
)

FROZEN_WEB_API_CLIENT_PATHS: Final[tuple[str, ...]] = (
    "web/lib/missionControl/missionControlCrossLaneApi.ts",
    "web/lib/missionControl/missionControlApprovalInboxApi.ts",
    "web/lib/missionControl/missionControlApprovalExecutionApi.ts",
    "web/lib/missionControl/missionControlEvidenceBundleApi.ts",
    "web/lib/missionControl/missionControlJobReplayApi.ts",
    "web/lib/missionControl/missionControlJobReplayResolveApi.ts",
    "web/lib/missionControl/missionControlReplayDeepLink.ts",
    "web/lib/missionControl/missionControlRerunPlanApi.ts",
    "web/lib/missionControl/missionControlOperationalMemoryApi.ts",
    "web/lib/missionControl/missionControlCrossSessionMemoryApi.ts",
    "web/lib/missionControl/missionControlKnowledgeSpacesApi.ts",
    "web/lib/missionControl/missionControlOperatorGuidanceApi.ts",
    "web/lib/missionControl/missionControlGovernanceInsightsApi.ts",
    "web/lib/missionControl/missionControlGovernanceSimulationApi.ts",
    "web/lib/missionControl/missionControlMissionStrategyApi.ts",
    "web/lib/missionControl/missionControlMissionOrchestrationApi.ts",
    "web/lib/missionControl/missionControlMissionReadinessReviewApi.ts",
    "web/lib/missionControl/missionControlGovernanceDeliberationApi.ts",
    "web/lib/missionControl/missionControlGovernanceCollaborationApi.ts",
    "web/lib/missionControl/missionControlGovernanceRoleArchitectureApi.ts",
    "web/lib/missionControl/missionControlGovernanceDoctrineApi.ts",
    "web/lib/missionControl/missionControlGovernancePolicyInterpretationApi.ts",
    "web/lib/missionControl/missionControlGovernanceCoherenceApi.ts",
    "web/lib/missionControl/missionControlGovernanceResilienceApi.ts",
    "web/lib/missionControl/missionControlGovernanceEvolutionApi.ts",
    "web/lib/missionControl/missionControlInstitutionalIdentityApi.ts",
    "web/lib/missionControl/missionControlInstitutionalExternalRelationsApi.ts",
    "web/lib/missionControl/missionControlInstitutionalExistentialRiskApi.ts",
    "web/lib/missionControl/missionControlConstitutionalEthicsApi.ts",
    "web/lib/missionControl/missionControlConstitutionalAuditApi.ts",
    "web/lib/missionControl/missionControlConstitutionalLegitimacyApi.ts",
    "web/lib/missionControl/missionControlConstitutionalPluralismApi.ts",
    "web/lib/missionControl/missionControlConstitutionalSynthesisApi.ts",
    "web/lib/missionControl/missionControlMissionPlanningApi.ts",
    "web/lib/missionControl/missionControlMissionPlanningDeliberationApi.ts",
    "web/lib/missionControl/missionControlHumanDecisionBoardApi.ts",
    "web/lib/missionControl/missionControlExecutionHandoffCoordinationApi.ts",
)

MISSION_CONTROL_OPERATOR_API_MODULE: Final[str] = "aethos_core/api/routes/mission_control.py"

ALLOWED_MC_OPERATOR_HTTP_ROUTES: Final[tuple[tuple[str, str], ...]] = (
    ("GET", "/mission-control/cross-lane/snapshot"),
    ("GET", "/mission-control/cross-lane/lane/{lane_id}/drilldown"),
    ("GET", "/mission-control/approval-inbox"),
    ("POST", "/mission-control/approval-inbox/execute"),
    ("POST", "/mission-control/approval-inbox/execute-terminal"),
    ("POST", "/mission-control/approval-inbox/execute-mutation"),
    ("POST", "/mission-control/approval-inbox/execute-serve"),
    ("POST", "/mission-control/approval-inbox/execute-operational-deployment"),
    ("POST", "/mission-control/approval-inbox/reject-operational-deployment"),
    ("GET", "/mission-control/approval-inbox/audit"),
    ("GET", "/mission-control/action-safety/review"),
    ("GET", "/mission-control/evidence-bundle"),
    ("GET", "/mission-control/job-replay"),
    ("GET", "/mission-control/job-replay/resolve"),
    ("GET", "/mission-control/rerun-plan"),
    ("GET", "/mission-control/operational-memory"),
    ("GET", "/mission-control/operational-memory/cross-session"),
    ("GET", "/mission-control/knowledge-spaces/search"),
    ("GET", "/mission-control/operator-guidance"),
    ("GET", "/mission-control/governance-insights"),
    ("GET", "/mission-control/governance-simulation"),
    ("GET", "/mission-control/mission-strategy"),
    ("GET", "/mission-control/mission-orchestration"),
    ("GET", "/mission-control/mission-readiness-review"),
    ("GET", "/mission-control/governance-deliberation"),
    ("POST", "/mission-control/governance-deliberation/record"),
    ("GET", "/mission-control/governance-collaboration"),
    ("POST", "/mission-control/governance-collaboration/record"),
    ("GET", "/mission-control/governance-role-architecture"),
    ("GET", "/mission-control/governance-doctrine"),
    ("POST", "/mission-control/governance-doctrine/record"),
    ("GET", "/mission-control/governance-policy-interpretation"),
    ("POST", "/mission-control/governance-policy-interpretation/record"),
    ("GET", "/mission-control/governance-coherence"),
    ("POST", "/mission-control/governance-coherence/record"),
    ("GET", "/mission-control/governance-resilience"),
    ("POST", "/mission-control/governance-resilience/record"),
    ("GET", "/mission-control/governance-evolution"),
    ("POST", "/mission-control/governance-evolution/record"),
    ("GET", "/mission-control/institutional-identity"),
    ("POST", "/mission-control/institutional-identity/record"),
    ("GET", "/mission-control/institutional-external-relations"),
    ("POST", "/mission-control/institutional-external-relations/record"),
    ("GET", "/mission-control/institutional-existential-risk"),
    ("POST", "/mission-control/institutional-existential-risk/record"),
    ("GET", "/mission-control/constitutional-ethics"),
    ("POST", "/mission-control/constitutional-ethics/record"),
    ("GET", "/mission-control/constitutional-audit"),
    ("POST", "/mission-control/constitutional-audit/record"),
    ("GET", "/mission-control/constitutional-legitimacy"),
    ("POST", "/mission-control/constitutional-legitimacy/record"),
    ("GET", "/mission-control/constitutional-pluralism"),
    ("POST", "/mission-control/constitutional-pluralism/record"),
    ("GET", "/mission-control/constitutional-synthesis"),
    ("POST", "/mission-control/constitutional-synthesis/record"),
    ("GET", "/mission-control/mission-planning"),
    ("POST", "/mission-control/mission-planning/record"),
    ("GET", "/mission-control/mission-planning-deliberation"),
    ("POST", "/mission-control/mission-planning-deliberation/record"),
    ("GET", "/mission-control/human-decision-board"),
    ("POST", "/mission-control/human-decision-board/record"),
    ("GET", "/mission-control/execution-handoff-coordination"),
    ("POST", "/mission-control/execution-handoff-coordination/record"),
    ("GET", "/mission-control/bounded-delivery-work-packages"),
    ("POST", "/mission-control/bounded-delivery-work-packages/record"),
    ("GET", "/mission-control/work-package-readiness-lane-admission"),
    ("POST", "/mission-control/work-package-readiness-lane-admission/record"),
    ("GET", "/mission-control/mission-authorization"),
    ("POST", "/mission-control/mission-authorization/record"),
    ("GET", "/mission-control/bounded-execution-participation"),
    ("POST", "/mission-control/bounded-execution-participation/record"),
    ("GET", "/mission-control/bounded-multi-agent-delivery-execution"),
    ("POST", "/mission-control/bounded-multi-agent-delivery-execution/record"),
    ("POST", "/mission-control/bounded-multi-agent-delivery-execution/run"),
    ("GET", "/mission-control/agent-execution-quality-throughput-metrics"),
    ("POST", "/mission-control/agent-execution-quality-throughput-metrics/record"),
    ("GET", "/mission-control/cross-repository-multi-agent-delivery-validation"),
    ("POST", "/mission-control/cross-repository-multi-agent-delivery-validation/record"),
    ("GET", "/mission-control/governed-merge-lifecycle"),
    ("POST", "/mission-control/governed-merge-lifecycle/record"),
    ("POST", "/mission-control/governed-merge-lifecycle/handoff"),
    ("GET", "/mission-control/governed-deploy-lifecycle"),
    ("POST", "/mission-control/governed-deploy-lifecycle/record"),
    ("POST", "/mission-control/governed-deploy-lifecycle/handoff"),
    ("GET", "/mission-control/governed-monitoring-lifecycle"),
    ("POST", "/mission-control/governed-monitoring-lifecycle/record"),
    ("POST", "/mission-control/governed-monitoring-lifecycle/escalate"),
    ("GET", "/mission-control/governed-rollback-lifecycle"),
    ("POST", "/mission-control/governed-rollback-lifecycle/record"),
    ("POST", "/mission-control/governed-rollback-lifecycle/handoff"),
    ("GET", "/mission-control/repository-knowledge-graph"),
    ("POST", "/mission-control/repository-knowledge-graph/record"),
    ("GET", "/mission-control/governed-application-generation"),
    ("POST", "/mission-control/governed-application-generation/record"),
    ("POST", "/mission-control/governed-application-generation/handoff"),
    ("GET", "/mission-control/multi-repository-engineering-intelligence"),
    ("POST", "/mission-control/multi-repository-engineering-intelligence/record"),
    ("GET", "/mission-control/cross-repository-product-evolution-intelligence"),
    ("POST", "/mission-control/cross-repository-product-evolution-intelligence/record"),
    ("GET", "/mission-control/autonomous-product-stewardship"),
    ("POST", "/mission-control/autonomous-product-stewardship/record"),
    ("GET", "/mission-control/autonomous-application-lifecycle-management"),
    ("POST", "/mission-control/autonomous-application-lifecycle-management/record"),
    ("GET", "/mission-control/autonomous-business-operating-system"),
    ("POST", "/mission-control/autonomous-business-operating-system/record"),
    ("GET", "/mission-control/autonomous-capability-registry"),
    ("POST", "/mission-control/autonomous-capability-registry/record"),
    ("GET", "/mission-control/multi-tenant-platform-foundation"),
    ("POST", "/mission-control/multi-tenant-platform-foundation/record"),
    ("GET", "/mission-control/tenant-onboarding-activation"),
    ("POST", "/mission-control/tenant-onboarding-activation/record"),
    ("GET", "/mission-control/identity-access-hardening"),
    ("POST", "/mission-control/identity-access-hardening/record"),
    ("GET", "/mission-control/provider-connection-experience"),
    ("POST", "/mission-control/provider-connection-experience/record"),
    ("GET", "/mission-control/channel-integration-foundation"),
    ("POST", "/mission-control/channel-integration-foundation/record"),
    ("GET", "/mission-control/billing-entitlements-foundation"),
    ("POST", "/mission-control/billing-entitlements-foundation/record"),
    ("GET", "/mission-control/customer-administration-console"),
    ("POST", "/mission-control/customer-administration-console/record"),
    ("GET", "/mission-control/customer-usage-audit-portal"),
    ("POST", "/mission-control/customer-usage-audit-portal/record"),
    ("GET", "/mission-control/payment-integration-readiness"),
    ("POST", "/mission-control/payment-integration-readiness/record"),
    ("GET", "/mission-control/saas-launch-readiness-assessment"),
    ("POST", "/mission-control/saas-launch-readiness-assessment/record"),
    ("GET", "/mission-control/customer-support-success-foundation"),
    ("POST", "/mission-control/customer-support-success-foundation"),
    ("GET", "/mission-control/public-product-experience"),
    ("POST", "/mission-control/public-product-experience"),
    ("GET", "/mission-control/limited-beta-launch-program"),
    ("POST", "/mission-control/limited-beta-launch-program"),
    ("GET", "/mission-control/launch-operations-center"),
    ("POST", "/mission-control/launch-operations-center"),
    ("GET", "/mission-control/public-launch-readiness-freeze"),
    ("POST", "/mission-control/public-launch-readiness-freeze"),
    ("GET", "/mission-control/launch-decision-package"),
    ("POST", "/mission-control/launch-decision-package"),
    ("GET", "/mission-control/post-launch-operations-baseline"),
    ("POST", "/mission-control/post-launch-operations-baseline"),
    ("GET", "/mission-control/pilotos-ui-trust-report-freeze"),
    ("POST", "/mission-control/pilotos-ui-trust-report-freeze/record"),
    ("GET", "/mission-control/governed-task-execution-coordination"),
    ("POST", "/mission-control/governed-task-execution-coordination/record"),
    ("GET", "/mission-control/gate-routed-package-outcome-review"),
    ("POST", "/mission-control/gate-routed-package-outcome-review/record"),
    ("GET", "/mission-control/governed-lane-entry-recommendation"),
    ("POST", "/mission-control/governed-lane-entry-recommendation/record"),
    ("GET", "/mission-control/governed-lane-readiness-board"),
    ("POST", "/mission-control/governed-lane-readiness-board/record"),
    ("GET", "/mission-control/human-lane-admission-decision"),
    ("POST", "/mission-control/human-lane-admission-decision/record"),
    ("GET", "/mission-control/gate-routed-lane-entry-handoff"),
    ("POST", "/mission-control/gate-routed-lane-entry-handoff/record"),
    ("GET", "/mission-control/frozen-gate-intake-preview"),
    ("POST", "/mission-control/frozen-gate-intake-preview/record"),
    ("GET", "/mission-control/frozen-gate-execution-request-adapter"),
    ("POST", "/mission-control/frozen-gate-execution-request-adapter/record"),
    ("GET", "/mission-control/governed-chat-command-invocation-from-handoff"),
    ("POST", "/mission-control/governed-chat-command-invocation-from-handoff/record"),
    ("POST", "/mission-control/governed-chat-command-invocation-from-handoff/invoke"),
    ("GET", "/mission-control/end-to-end-repo-development-pilot-harness"),
    ("POST", "/mission-control/end-to-end-repo-development-pilot-harness/record"),
    ("POST", "/mission-control/end-to-end-repo-development-pilot-harness/run"),
    ("GET", "/mission-control/repo-pilot-readiness-dashboard"),
    ("POST", "/mission-control/repo-pilot-readiness-dashboard/record"),
    ("GET", "/mission-control/pilot-validation-trust-board"),
    ("POST", "/mission-control/pilot-validation-trust-board/record"),
    ("GET", "/mission-control/issue-intent-alignment"),
    ("POST", "/mission-control/issue-intent-alignment/record"),
    ("GET", "/mission-control/dogfood-pilot-trust-report-freeze"),
    ("POST", "/mission-control/dogfood-pilot-trust-report-freeze/record"),
    ("GET", "/mission-control/dogfood-pilot-gate-closure"),
    ("GET", "/mission-control/independent-repository-trust-expansion"),
    ("POST", "/mission-control/independent-repository-trust-expansion/record"),
    ("GET", "/mission-control/pilotos-ui-pilot-arc-orchestrator"),
    ("POST", "/mission-control/pilotos-ui-pilot-arc-orchestrator/record"),
    ("POST", "/mission-control/pilotos-ui-pilot-arc-orchestrator/run"),
    ("GET", "/mission-control/atlas-trader-pilot-arc-orchestrator"),
    ("POST", "/mission-control/atlas-trader-pilot-arc-orchestrator/record"),
    ("POST", "/mission-control/atlas-trader-pilot-arc-orchestrator/run"),
    ("GET", "/mission-control/atlas-trader-trust-report-freeze"),
    ("POST", "/mission-control/atlas-trader-trust-report-freeze/record"),
    ("GET", "/mission-control/nexora-pilot-arc-orchestrator"),
    ("POST", "/mission-control/nexora-pilot-arc-orchestrator/record"),
    ("POST", "/mission-control/nexora-pilot-arc-orchestrator/run"),
    ("GET", "/mission-control/nexora-trust-report-freeze"),
    ("POST", "/mission-control/nexora-trust-report-freeze/record"),
    ("GET", "/mission-control/continuous-product-improvement"),
    ("POST", "/mission-control/continuous-product-improvement"),
    ("GET", "/mission-control/customer-feedback-intelligence"),
    ("POST", "/mission-control/customer-feedback-intelligence"),
    ("GET", "/mission-control/customer-journey-intelligence"),
    ("POST", "/mission-control/customer-journey-intelligence"),
    ("GET", "/mission-control/customer-value-realization-intelligence"),
    ("POST", "/mission-control/customer-value-realization-intelligence"),
    ("GET", "/mission-control/enterprise-operating-review-intelligence"),
    ("POST", "/mission-control/enterprise-operating-review-intelligence"),
    ("GET", "/mission-control/enterprise-program-intelligence"),
    ("POST", "/mission-control/enterprise-program-intelligence"),
    ("GET", "/mission-control/executive-decision-intelligence"),
    ("POST", "/mission-control/executive-decision-intelligence"),
    ("GET", "/mission-control/executive-operating-system-dashboard"),
    ("POST", "/mission-control/executive-operating-system-dashboard"),
    ("GET", "/mission-control/growth-adoption-intelligence"),
    ("POST", "/mission-control/growth-adoption-intelligence"),
    ("GET", "/mission-control/issue-intake-scope-fidelity"),
    ("GET", "/mission-control/organizational-effectiveness-intelligence"),
    ("POST", "/mission-control/organizational-effectiveness-intelligence"),
    ("GET", "/mission-control/product-analytics-foundation"),
    ("POST", "/mission-control/product-analytics-foundation"),
    ("GET", "/mission-control/product-market-fit-intelligence"),
    ("POST", "/mission-control/product-market-fit-intelligence"),
    ("GET", "/mission-control/strategic-planning-intelligence"),
    ("POST", "/mission-control/strategic-planning-intelligence"),
    ("GET", "/mission-control/strategic-portfolio-intelligence"),
    ("POST", "/mission-control/strategic-portfolio-intelligence"),
)

FORBIDDEN_MC_OPERATOR_CAPABILITIES: Final[tuple[str, ...]] = (
    "deploy",
    "restart",
    "merge",
    "execute_mutation",
    "railway_mutation",
    "provider_mutation_bypass",
    "direct_github_push_from_ui",
    "direct_pr_open_from_ui",
    "autonomous_rollout_promotion",
)

FORBIDDEN_UI_BUTTON_LABEL_PATTERNS: Final[tuple[re.Pattern[str], ...]] = tuple(
    re.compile(p, re.IGNORECASE)
    for p in (
        r">\s*Deploy\b",
        r">\s*Restart\b",
        r">\s*Merge\b",
        r">\s*Execute\s*</",
        r">\s*Run\s+mutation\b",
        r">\s*Promote\b",
        r">\s*Rollback\b",
    )
)

ALLOWED_UI_APPROVAL_GATE_IDS: Final[tuple[str, ...]] = (
    "planning_approved",
    "branch_create",
    "patch_proposal_approved",
    "workspace_apply",
    "github_preflight_approved",
)

VIEW_ONLY_INBOX_GATE_IDS: Final[tuple[str, ...]] = (
    "branch_push_completed",
    "github_pr_opened",
    "governed_execution",
)

MISSION_CONTROL_UI_ROUTE_MATRIX: Final[tuple[dict[str, str], ...]] = (
    {
        "view_id": "cross-lane-operations",
        "fix": "FIX 129–130",
        "mode": "read_only",
        "backend_owner": "mission_control.cross_lane.snapshot_service",
        "api": "GET /api/v1/mission-control/cross-lane/snapshot",
        "mutation": "none",
    },
    {
        "view_id": "cross-lane-operations",
        "fix": "FIX 131",
        "mode": "read_only",
        "backend_owner": "mission_control.cross_lane.lane_drilldown_service",
        "api": "GET /api/v1/mission-control/cross-lane/lane/{lane_id}/drilldown",
        "mutation": "none",
    },
    {
        "view_id": "approval-inbox",
        "fix": "FIX 132",
        "mode": "read_only",
        "backend_owner": "mission_control.approval_inbox.approval_inbox_service",
        "api": "GET /api/v1/mission-control/approval-inbox",
        "mutation": "none",
    },
    {
        "view_id": "approval-inbox",
        "fix": "FIX 133–134",
        "mode": "governed_approval",
        "backend_owner": "mission_control.approval_inbox.approval_execution_service",
        "api": "POST /api/v1/mission-control/approval-inbox/execute",
        "mutation": "via_chat_governance_only",
    },
    {
        "view_id": "approval-inbox",
        "fix": "FIX 134",
        "mode": "read_only",
        "backend_owner": "mission_control.approval_inbox.approval_audit_service",
        "api": "GET /api/v1/mission-control/approval-inbox/audit",
        "mutation": "none",
    },
    {
        "view_id": "approval-inbox",
        "fix": "FIX 134",
        "mode": "read_only",
        "backend_owner": "mission_control.approval_inbox.action_safety_review",
        "api": "GET /api/v1/mission-control/action-safety/review",
        "mutation": "none",
    },
    {
        "view_id": "cross-lane-operations",
        "fix": "FIX 136",
        "mode": "read_only",
        "backend_owner": "mission_control.evidence_bundle.evidence_bundle_service",
        "api": "GET /api/v1/mission-control/evidence-bundle",
        "mutation": "none",
    },
    {
        "view_id": "mission-job-replay",
        "fix": "FIX 137",
        "mode": "read_only",
        "backend_owner": "mission_control.job_replay.job_replay_service",
        "api": "GET /api/v1/mission-control/job-replay",
        "mutation": "none",
    },
)

MISSION_CONTROL_UI_DOC_PATHS: Final[tuple[str, ...]] = (
    "docs/MISSION_CONTROL_INDEX.md",
    "docs/MISSION_CONTROL_EVIDENCE_BUNDLE_EXPORT.md",
    "docs/MISSION_CONTROL_JOB_REPLAY.md",
    "docs/MISSION_CONTROL_RERUN_PLANNING.md",
    "docs/MISSION_CONTROL_OPERATIONAL_MEMORY.md",
    "docs/MISSION_CONTROL_CROSS_SESSION_MEMORY.md",
    "docs/MISSION_CONTROL_KNOWLEDGE_SPACES.md",
    "docs/MISSION_CONTROL_OPERATOR_GUIDANCE.md",
    "docs/MISSION_CONTROL_GOVERNANCE_INSIGHTS.md",
    "docs/MISSION_CONTROL_GOVERNANCE_SIMULATION.md",
    "docs/MISSION_CONTROL_MISSION_STRATEGY.md",
    "docs/MISSION_CONTROL_MISSION_ORCHESTRATION.md",
    "docs/MISSION_CONTROL_MISSION_READINESS_REVIEW.md",
    "docs/MISSION_CONTROL_GOVERNANCE_DELIBERATION.md",
    "docs/MISSION_CONTROL_GOVERNANCE_COLLABORATION.md",
    "docs/MISSION_CONTROL_GOVERNANCE_ROLE_ARCHITECTURE.md",
    "docs/MISSION_CONTROL_GOVERNANCE_DOCTRINE.md",
    "docs/MISSION_CONTROL_GOVERNANCE_POLICY_INTERPRETATION.md",
    "docs/MISSION_CONTROL_GOVERNANCE_COHERENCE.md",
    "docs/MISSION_CONTROL_GOVERNANCE_RESILIENCE.md",
    "docs/MISSION_CONTROL_GOVERNANCE_EVOLUTION.md",
    "docs/MISSION_CONTROL_INSTITUTIONAL_IDENTITY.md",
    "docs/MISSION_CONTROL_INSTITUTIONAL_EXTERNAL_RELATIONS.md",
    "docs/MISSION_CONTROL_INSTITUTIONAL_EXISTENTIAL_RISK.md",
    "docs/MISSION_CONTROL_CONSTITUTIONAL_ETHICS.md",
    "docs/MISSION_CONTROL_CONSTITUTIONAL_AUDIT.md",
    "docs/MISSION_CONTROL_CONSTITUTIONAL_LEGITIMACY.md",
    "docs/MISSION_CONTROL_CONSTITUTIONAL_PLURALISM.md",
    "docs/MISSION_CONTROL_CONSTITUTIONAL_SYNTHESIS.md",
    "docs/MISSION_CONTROL_MISSION_PLANNING.md",
    "docs/MISSION_CONTROL_MISSION_PLANNING_DELIBERATION.md",
    "docs/MISSION_CONTROL_HUMAN_DECISION_BOARD.md",
    "docs/MISSION_CONTROL_EXECUTION_HANDOFF_COORDINATION.md",
    "docs/MISSION_CONTROL_PHASE_2_UI_FREEZE.md",
    "docs/MISSION_CONTROL_OPERATOR_RUNBOOK.md",
    "docs/MISSION_CONTROL_TROUBLESHOOTING.md",
    "docs/MISSION_CONTROL_CROSS_LANE_OBSERVABILITY.md",
    "docs/MISSION_CONTROL_SESSION_AWARENESS.md",
    "docs/MISSION_CONTROL_LANE_DRILLDOWN.md",
    "docs/MISSION_CONTROL_APPROVAL_INBOX.md",
    "docs/MISSION_CONTROL_APPROVAL_EXECUTION.md",
    "docs/MISSION_CONTROL_APPROVAL_AUDIT.md",
)

# Re-export for certification (single import surface).
FORBIDDEN_PROVIDER_SYMBOLS: Final[tuple[str, ...]] = FORBIDDEN_DIRECT_PROVIDER_CALLS
UI_APPROVAL_CHAT_ENTRYPOINT: Final[str] = REQUIRED_UI_APPROVAL_ENTRYPOINT
FORBIDDEN_UI_CONTROLS: Final[tuple[str, ...]] = FORBIDDEN_MC_UI_CONTROLS_FIX_134
